import React from 'react'

import type { Metadata } from 'next'

import '..styles/globals.css'

import { Bai_Jamjuree } from 'next/font/google'

const baiJamjuree = Bai_Jamjuree({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify the weights you need
  variable: '--font-bai-jamjuree', // Optional: define a CSS variable
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${baiJamjuree.variable} antialiased`}>{children}</body>
    </html>
  )
}
