import React from 'react'
import type { Metadata } from 'next'
import '@/styles/global.scss'
import { Bai_Jamjuree } from 'next/font/google'
import { Providers } from '@/providers/Providers'

const baiJamjuree = Bai_Jamjuree({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-bai-jamjuree',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Fragment kullanarak dönüş yapmak yerine doğrudan JSX elemanını döndürün
  return React.createElement(
    'html',
    { lang: 'en' },
    React.createElement(
      'body',
      {
        className: `${baiJamjuree.variable} antialiased`,
      },
      React.createElement(Providers, null, children),
    ),
  )
}
